<?php

namespace App\Forms;

use Kris\LaravelFormBuilder\Form;

class FieldForm extends Form
{
	public function buildForm()
	{
		$this->name();
		$this->required();
		$this->description();
		$this->key();
		$this->default();
	}

	private function name()
	{
		$this->add('name', 'text', [
			'label'      => 'Name',
			'rules'      => ['required'],
			'help_block' => [
				'text' => 'User friendly name to identify the field',
			],
		]);
	}

	private function required()
	{
		$this->add('required', 'checkbox', [
			'label'      => 'Required',
			'help_block' => [
				'text' => 'If this field is required to be in the rendered config file. If a field is required and no constants with it\' key are present in the configs, the default value will be rendered.',
			],
		]);
	}

	private function description()
	{
		$this->add('description', 'summernote', [
			'label'      => 'Description',
			'help_block' => [
				'text' => 'Description of what this field is, allowed values, what it does, etc.',
			],
		]);
	}

	private function key()
	{
		$this->add('key', 'text', [
			'label'      => 'Key',
			'rules'      => ['required'],
			'help_block' => [
				'text' => 'Identification for the constants that will be generated by this field.',
			],
		]);
	}

	private function default()
	{
		$this->add('default', 'text', [
			'label'      => 'Default value',
			'help_block' => [
				'text' => 'Default value of this field when no constants with the same key as present in the rendering config',
			],
		]);
	}
}
